version: '3.1'

services:
  api:
    container_name: fast-track-auto-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/app
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
